# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.

name: Node.js CI

on:
  push:
    branches: [ "master"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [v12.22.9]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      
